var musixMatchApiKey = '27fd8a413c8f5837346998c3a41c1b2d';

var categories = 
{
	happy:["happy", "smile", "money"],
	sad:["sad", "depressed", "lonely", "sorry"],
	peace:["peace", "calm", "forgive"],
	fun:["fun", "funny", "play"],
	love:["love", "heart", "cheat", "beauty", "life"],
	anger:["angry", "envy", "hate"],
	sex:["passion", "excited", "sexy"],
	crazy:["crazy", "wierd", "insane", "silly"],
	cheerful:["cheer", "rhythm", "dance", "bass", "melody"],
	powerful:["power", "rock", "hard", "jump"],
	good:["accepted","accomplished","admiration","adorable","affectionate","alive","amused","anticipate","appreciated","authoritative","awake","awe","awed","blissful","bold","bouncy","brilliant","brooding","calm","careful","cautious","cheerful","chilled","chipper","clear","clever","comical","compassionate","confident","contemplative","content","cool","cordial","crazy","curious","defensive","delighted","determined","devious","devoted","dignified","disciplined","ditzy","dreamy","drunk","dutiful","dynamic","ecstatic","elated","empowered","energetic","enlightened","enthralled","excited","exhilarated","exhilaration","exuberance","fearless","feisty","flattered","flirty","forgiving","friendly","gay","geeky","generous","gentle","giggly","glee","good","grateful","happy","harmonious","heroic","high","honest","honored","hope","hopeful","hot","humorous","hyper","idyllic","imaginative","impressed","inclusive","indescribable","innocent","inquisitive","insightful","inspired","intuitive","joy","joyful","joyous","jubilant","kind","kindred","liberating","light-hearted","lively","love","loved","loving","lucky","meek","mellow","mischievous","mollified","mysterious","natural","naughty","nostalgic","okay","optimistic","outstanding","overjoyed","passionate","patient","peaceful","perky","persistent","playful","pleased","powerful","pride","quixotic","rational","recumbent","refreshed","rejuvenated","relaxed","reliable","relief","relieved","resistant","resolved","reverent","romantic","satiated","satisfied","satisfy","sedated","sentimental","silly","sixthsense","skillful","sleepy","smart","sure","surprised","sweet","sympathetic","tempted","tender","thankful","thoughtful","touched","trustful","understood","valiant","vibrant","victorious","vigorous","vivacious","vocal","vociferous","warm","wary","welcoming","wise","wonder","worthy","youthful","zeal","zealous"],
	bad:["afraid","aggravated","aggressive","alarmed","alone","angry","annoyed","anxiety","anxious","apathetic","apologetic","apprehension","apprehensive","arrogance","ashamed","aversion","awful","bad","barren","belligerent","bewildered","bitchy","bitter","bittersweet","blank","blue","blunt","bored","bullying","callous","chaotic","clueless","cold","combative","complacent","confining","confused","contemptuous","contrary","covetous","cranky","crappy","cross","cruelty","crushed","cynical","dainty","dark","defeated","defiant","dejected","delusional","demented","depressed","desolate","despair","despondent","devastated","dirty","disagreeable","disappointed","discontent","discontented","disgrace","disgruntled","disgust","distaste","distressed","dorky","doubtful","drained","dread","dreary","embarrassed","enraged","envious","envy","evil","exanimate","exhausted","fatalistic","fear","fearful","fierce","folksy","foreboding","forgetful","forlorn","frustrated","full","furious","fury","futile","giddy","gloomy","greedy","groggy","grumpy","guilty","harsh","hatred","haughty","haunting","heartbroken","hopeless","horror","hostile","hunch","hungry","ignored","impartial","impatient","inconsiderate","indifferent","infuriated","insensitivity","insidious","intimidated","intolerance","irate","ire","irritate","irritated","isolated","jealous","jumpy","lazy","lethargic","listless","loathing","lonely","mad","madness","malice","mean","melancholic","melancholy","merciless","moody","morose","mournful","nasty","nauseated","nerdy","nervous","nightmarish","numb","obnoxious","obstinate","outraged","overwhelmed","pain","painful","panic","paranoid","pensive","perturb","pessimistic","pissed-off","pity","predatory","querulous","rage","rapturous","regret","rejected","reluctant","repentant","repulsive","resent","resigned","restless","restrained","revulsion","ridiculed","rough","rude","rushed","sad","scared","scornful","serious","severe","shame","shocked","sick","somber","sorrow","spite","stressed","stubborn","suspenseful","tense","terrifying","threatening","tired","traumatized","trepidation","uncertain","uncomfortable","unhappy","unsatisfied","vengeful","vindictive","violent","weary","weird","wicked","woeful","worried","wrath"]
};